print("Calculator v0.1")
a: float = float(input("Enter the first number: "))
b: float = float(input("Enter the second number: "))

print("Addition: ", a + b)
print("subtraction:", a - b)
print("multiplication:", a * b)
print("division:", a / b)
print("power:", a**b)
print("division:", a // b)
